#--------------------- DB ----------------------
# DB Connection with the uri (host)
client: "mongodb://localhost:27017/"

# db name
db: "aiot_course"

# db collection
col: "Data"


#--------------------- Dataframe Instantiation ----------------------
# Dataframe columns list
#order_acc: ["x-axis (g)", "y-axis (g)", "z-axis (g)"]
#rename_acc: ["acc_x", "acc_y", "acc_z"]
#order_gyr: ["x-axis (deg/s)", "y-axis (deg/s)", "z-axis (deg/s)"]
#rename_gyr: [ "gyr_x", "gyr_y", "gyr_z"]
order: ['accel_x', 'accel_y', 'accel_z', 'gyro_x', 'gyro_y', 'gyro_z']
rename: ['acc_x', 'acc_y', 'acc_z', 'gyr_x', 'gyr_y', 'gyr_z']

#--------------------- Dataset Local Storage ----------------------
# dataset location
data_path: "c:/Users/spigg/Desktop/aiot_project/data"
# single data instance location path to experiment with the data engineering process and visualization
single_instance_path: "c:/Users/spigg/Desktop/aiot_project/instance"


#--------------------- Data Engineering ----------------------
# sliding window algorithm parameters
sliding_window:
  ws: 150
  overlap: 5
  w_type: "hann"
  w_center: True
  print_stats: True

# window to handle for visualization purposes
x_number: 2

# filtering parameterization
filter:
  order: 5
  wn: 0.1
  type: "lowpass"


#--------------------- $ Data Preparation ----------------------
# Dimensionality reduction
PCA:
  n_comp_2: 2
  n_comp_3: 3

#--------------------- Learning ----------------------
# Classifier - Statistical
classifier:
  SVC:
    C: 10
    kernel: "rbf"
    gamma: 0.5
  # classifier 2
    # put your other Statistical-related classifier params here
  # classifier 3
    # put your other Statistical-related classifier params here

# Parameter Grid for Fine-tuning, for instance, a Grid Search classifier
fine_tune:
  param_grid: [
    {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
    {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
   ]
  cv: 5
  verbose: 1

# Classifier - Neural Network
fit:
  epochs:
  batch:
  verbose: "auto"